
*** Variables ***
${CHAMP_USERNAME_XPATH}                                //input[@formcontrolname='username']
${CHAMP_HICODE_XPATH}                                  //input[@formcontrolname='X_HI_CODE']
${CHAMP_MDP_XPATH}                                     //input[@formcontrolname='password']
${BOUTON_SE_CONNECTER_XPATH}                           //button[contains(.,'Connexion')]

${BOUTON_CONFIRM_XPATH}                                //button[contains(.,'__1__')]